name = "DifferentialDynamicsModels"
uuid = "cb52cc87-d0c7-5933-bad1-08679d8b4c67"
authors = ["Ed Schmerling <ednerd@gmail.com>"]
version = "1.0.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
StaticArrays = "≥ 0.8.2"
julia = "≥ 0.7.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
